on: [push, pull_request]
jobs:
  autoformat_job:
    runs-on: ubuntu-latest
    name: clang formatter
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: clang-format
      id: format
      uses: SKIRT/auto-format@master
    - name: Autocommit
      if: steps.format.outputs.status == 'changed'
      run: |
        git config --global user.name 'auto-format'
        git config --global user.email 'auto-format@auto.format'
        git commit -am "Autoformat"
        git push
